// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Data;

#nullable disable

namespace MyShop.Migrations
{
    [DbContext(typeof(MyShopContext))]
    partial class MyShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyShop.Data.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Category 1",
                            Description = "This is the description for Product 1",
                            ImagePath = "",
                            Name = "Product 1",
                            Price = 10.99
                        },
                        new
                        {
                            ID = 2,
                            Category = "Category 2",
                            Description = "This is the description for Product 2",
                            ImagePath = "",
                            Name = "Product 2",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            ID = 3,
                            Category = "Category 1",
                            Description = "This is the description for Product 3",
                            ImagePath = "",
                            Name = "Product 3",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            ID = 4,
                            Category = "Category 3",
                            Description = "This is the description for Product 4",
                            ImagePath = "",
                            Name = "Product 4",
                            Price = 15.99
                        },
                        new
                        {
                            ID = 5,
                            Category = "Category 2",
                            Description = "This is the description for Product 5",
                            ImagePath = "",
                            Name = "Product 5",
                            Price = 12.49
                        },
                        new
                        {
                            ID = 6,
                            Category = "Category 1",
                            Description = "This is the description for Product 6",
                            ImagePath = "",
                            Name = "Product 6",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ID = 7,
                            Category = "Category 3",
                            Description = "This is the description for Product 7",
                            ImagePath = "",
                            Name = "Product 7",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            ID = 8,
                            Category = "Category 2",
                            Description = "This is the description for Product 8",
                            ImagePath = "",
                            Name = "Product 8",
                            Price = 14.99
                        },
                        new
                        {
                            ID = 9,
                            Category = "Category 1",
                            Description = "This is the description for Product 9",
                            ImagePath = "",
                            Name = "Product 9",
                            Price = 11.99
                        },
                        new
                        {
                            ID = 10,
                            Category = "Category 3",
                            Description = "This is the description for Product 10",
                            ImagePath = "",
                            Name = "Product 10",
                            Price = 8.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
